config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Sail::Engine => '/sail'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  # B2C end points pages
  get 'identity/help', to: 'static_pages#help'
  get 'identity/forgotusername', to: 'test_case_callbacks#show'
  get 'identity/signinl3', to: 'test_case_callbacks#show'
  get 'identity/signinl2', to: 'test_case_callbacks#show'
  # if you're using the aggregate profile management page
  get 'identity/maintainmobile', to: 'test_case_callbacks#show'
  get 'identity/changeusername', to: 'test_case_callbacks#show'
  get 'identity/changepassword', to: 'test_case_callbacks#show'
  get 'identity/maintainquestions', to: 'test_case_callbacks#show'
  get 'identity/deleteaccount', to: 'test_case_callbacks#show'
  # B2C endpoint redirects
  post 'test_case_callbacks/:id', to: 'test_case_callbacks#show'
  # *********************************
  get '/confidential', to: 'static_pages#confidential'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get  '/b2c_user',           to: 'b2c_api#search'
  get  '/b2c_user/:id',  to: 'b2c_api#show'
  get '/servicehints',  to: 'servicehints#add'
  post '/servicehints/new',  to: 'servicehints#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/openid', to: 'top#show'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :test_cases, only: :show
  resources :test_case_callbacks, only: :show
end
#get "/foo", to: redirect('/bar')
#test use conole and app object >> app.clients_path, >>app.clients_url

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    [Site Owner: J.Sutcliffe] 
    [RP:<%= Sail.get("LoA") %> User:<%= session[:jwttokenloa] %> Identity:<%= session[:jwttokenemail] %>]
  </small>
  <nav>
    <ul>
       <li><%= link_to "Admin", login_path %></li>
       <li><%= link_to "B2C Test", external_url_builder.B2C_url %></li>
       <li><%= link_to "Swag", external_url_builder.SWAG_url %></li>
       <li><%= link_to "CSA", external_url_builder.CSA_url %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
 
  <div class="container">
  
    <%= link_to " Relying Party", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
           <li><%= link_to "Confidential", confidential_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "BUID maintain security questions", test_case_path("maintainsecurity") %></li>
              <li><%= link_to "BUID change password", test_case_path("changepassword") %></li>
              <li><%= link_to "BUID maintain mobile", test_case_path("maintainmobile") %></li>
              <li><%= link_to "BUID change username", test_case_path("username") %></li>
              <li><%= link_to "BUID delete account", test_case_path("deleteuser") %></li>
              <li><%= link_to "BUID profile mgmt", test_case_path("profile") %></li>
                  <% if current_user.admin? %>
       
                  <li><%= link_to "ADMIN Search B2C", b2c_user_path %></li>
                  <li><%= link_to "ADMIN Service Hint", servicehints_path %></li>
                  <li><%= link_to "ADMIN User Database", rails_admin_path %></li>
                   <li><%= link_to "ADMIN Sail", sail_path %></li>
                   <% end %>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
 <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_wrapper.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />
    <title>B2C Bounce</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= content_tag :div, id: :wrapper, class: local_assigns[:wrapper_class] do %>
      <header id="header">
      </header>


      <div id="main">
        <div class="inner">
          <%= yield %>
        </div>
      </div>

      <footer id="footer">
    
      </footer>
    <% end %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
     <%= render 'layouts/rails_default' %>
     <%= render 'layouts/shim' %>
  </head>
 <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/popup.html.erb
<%= render 'layouts/wrapper', wrapper_class: :popup do %>
  <%= yield %>
<% end %>